substitutions:
  name: "avatar-smartplug"
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "955"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: blakemlloyd.avatar-smartplug
    version: "1.0"

dashboard_import:
  package_import_url: github://blakemlloyd/esphome-project-templates/avatar-smartplug.yaml

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "${ap_password}"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "${name}-button"
    on_press:
      then:
        switch.toggle: relay
    
switch:
  - platform: gpio
    id: relay
    name: "${name}-relay"
    pin: GPIO15
    restore_mode: ALWAYS_OFF 
    on_turn_on:
      then:
        - switch.turn_on: led
    on_turn_off:
      then:
        - switch.turn_off: led
  - platform: gpio
    name: "${name}-led"
    pin: GPIO2
    inverted: True
    restore_mode: ALWAYS_OFF 
    id: led
    
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${name}-amperage"
      unit_of_measurement: A
    voltage:
      name: "${name}-voltage"
      unit_of_measurement: V
    power:
      name: "${name}-wattage"
      id: "${name}-wattage"
      unit_of_measurement: W
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${name}-total-daily-energy"
    power_id: "${name}-wattage"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh